spring:
  application:
    name: feign-mock-server

server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 15  #eureka服务受到最后一次心跳后等待时间上限，默认值 90
    lease-renewal-interval-in-seconds: 10  #向eureka服务发送心跳的时间间隔，默认值 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3 #3秒钟去eureka拿一次微服务注册实例，默认值 30